const button = {
  colors: {
    primary: {
      color: get => get('palette', 'white'),
      colorOutline: get => get('palette', 'primary'),
      colorOutlineHover: get => get('palette', 'white'),
      backgroundColor: get => get('palette', 'primary'),
      backgroundColorDisabled: get => get('palette', 'primary'),
      backgroundColorHoverFocus: get => get('palette', 'primaryDarker'),
      backgroundColorActive: get => get('palette', 'primaryDark'),
      borderColor: get => get('palette', 'primary'),
      borderColorDisabled: get => get('palette', 'primary'),
      borderColorHoverFocus: get => get('palette', 'primaryDark'),
      borderColorActive: get => get('palette', 'primaryDark'),
      boxShadow: get => get('palette', 'primaryBoxShadow'),
    },
    secondary: {
      color: get => get('palette', 'white'),
      colorOutline: get => get('palette', 'secondary'),
      colorOutlineHover: get => get('palette', 'white'),
      backgroundColor: get => get('palette', 'secondary'),
      backgroundColorDisabled: get => get('palette', 'secondary'),
      backgroundColorHoverFocus: get => get('palette', 'secondaryDarker'),
      backgroundColorActive: get => get('palette', 'secondary'),
      borderColor: get => get('palette', 'secondary'),
      borderColorDisabled: get => get('palette', 'secondary'),
      borderColorHoverFocus: get => get('palette', 'secondaryDark'),
      borderColorActive: get => get('palette', 'secondaryDark'),
      boxShadow: get => get('palette', 'secondaryBoxShadow'),
    },
    success: {
      color: get => get('palette', 'white'),
      colorOutline: get => get('palette', 'success'),
      colorOutlineHover: get => get('palette', 'white'),
      backgroundColor: get => get('palette', 'success'),
      backgroundColorDisabled: get => get('palette', 'success'),
      backgroundColorHoverFocus: get => get('palette', 'successDarker'),
      backgroundColorActive: get => get('palette', 'successDark'),
      borderColor: get => get('palette', 'success'),
      borderColorDisabled: get => get('palette', 'success'),
      borderColorHoverFocus: get => get('palette', 'successDark'),
      borderColorActive: get => get('palette', 'successDark'),
      boxShadow: get => get('palette', 'successBoxShadow'),
    },
    danger: {
      color: get => get('palette', 'white'),
      colorOutline: get => get('palette', 'danger'),
      colorOutlineHover: get => get('palette', 'white'),
      backgroundColor: get => get('palette', 'danger'),
      backgroundColorDisabled: get => get('palette', 'danger'),
      backgroundColorHoverFocus: get => get('palette', 'dangerDarker'),
      backgroundColorActive: get => get('palette', 'dangerDark'),
      borderColor: get => get('palette', 'danger'),
      borderColorDisabled: get => get('palette', 'danger'),
      borderColorHoverFocus: get => get('palette', 'dangerDark'),
      borderColorActive: get => get('palette', 'dangerDark'),
      boxShadow: get => get('palette', 'dangerBoxShadow'),
    },
    warning: {
      color: get => get('palette', 'darkerDarker'),
      colorOutline: get => get('palette', 'warning'),
      colorOutlineHover: get => get('palette', 'darkerDarker'),
      backgroundColor: get => get('palette', 'warning'),
      backgroundColorDisabled: get => get('palette', 'warning'),
      backgroundColorHoverFocus: get => get('palette', 'warningDarker'),
      backgroundColorActive: get => get('palette', 'warningDark'),
      borderColor: get => get('palette', 'warning'),
      borderColorDisabled: get => get('palette', 'warning'),
      borderColorHoverFocus: get => get('palette', 'warningDark'),
      borderColorActive: get => get('palette', 'warningDark'),
      boxShadow: get => get('palette', 'warningBoxShadow'),
    },
    info: {
      color: get => get('palette', 'white'),
      colorOutline: get => get('palette', 'info'),
      colorOutlineHover: get => get('palette', 'white'),
      backgroundColor: get => get('palette', 'info'),
      backgroundColorDisabled: get => get('palette', 'info'),
      backgroundColorHoverFocus: get => get('palette', 'infoDarker'),
      backgroundColorActive: get => get('palette', 'infoDark'),
      borderColor: get => get('palette', 'info'),
      borderColorDisabled: get => get('palette', 'info'),
      borderColorHoverFocus: get => get('palette', 'infoDark'),
      borderColorActive: get => get('palette', 'infoDark'),
      boxShadow: get => get('palette', 'infoBoxShadow'),
    },
    light: {
      color: get => get('palette', 'darkerDarker'),
      colorOutline: get => get('palette', 'light'),
      colorOutlineHover: get => get('palette', 'darkerDarker'),
      backgroundColor: get => get('palette', 'light'),
      backgroundColorDisabled: get => get('palette', 'light'),
      backgroundColorHoverFocus: get => get('palette', 'lightDarker'),
      backgroundColorActive: get => get('palette', 'lightDark'),
      borderColor: get => get('palette', 'light'),
      borderColorDisabled: get => get('palette', 'light'),
      borderColorHoverFocus: get => get('palette', 'lightDark'),
      borderColorActive: get => get('palette', 'lightDark'),
      boxShadow: get => get('palette', 'lightBoxShadow'),
      toggle: {
        color: get => get('palette', 'dark50Alpha'),
        borderColor: get => get('palette', 'dark10Alpha'),
        colorHoverFous: get => get('palette', 'dark50Alpha'),
        borderColorHoverFous: get => get('palette', 'dark10Alpha'),
      },
    },
    dark: {
      color: get => get('palette', 'white'),
      colorOutline: get => get('palette', 'dark'),
      colorOutlineHover: get => get('palette', 'white'),
      backgroundColor: get => get('palette', 'dark'),
      backgroundColorDisabled: get => get('palette', 'dark'),
      backgroundColorHoverFocus: get => get('palette', 'darkDarker'),
      backgroundColorActive: get => get('palette', 'darkDark'),
      borderColor: get => get('palette', 'dark'),
      borderColorDisabled: get => get('palette', 'dark'),
      borderColorHoverFocus: get => get('palette', 'darkDark'),
      borderColorActive: get => get('palette', 'darkDark'),
      boxShadow: get => get('palette', 'darkBoxShadow'),
      toggle: {
        color: get => get('palette', 'white50Alpha'),
        borderColor: get => get('palette', 'white10Alpha'),
        colorHoverFous: get => get('palette', 'white50Alpha'),
        borderColorHoverFous: get => get('palette', 'white10Alpha'),
      },
    },
    default: get => get('button', 'colors', 'secondary'),
  },
  margin: {
    blockTop: '0.5rem',
    dropDownToggleLeft: '0255rem',
  },
  padding: {
    sm: '0.25rem 0.5rem',
    lg: '0.5rem 1rem',
    default: '0.375rem 0.75rem',

    splitSmRight: '0.375rem',
    splitSmLeft: '0.375rem',
    splitLgRight: '0.75rem',
    splitLgLeft: '0.75rem',
    splitDefaultRight: '0.5625rem',
    splitDefaultLeft: '0.5625rem',
  },
  fontSize: get => get('globals', 'fontSize'),
  border: get => get('globals', 'border'),
  borderRadius: get => get('globals', 'borderRadius'),
};

export default button;
