import globals from './globals';
import palette from './palette';

const button = {
  borderRadius: globals.borderRadius,
  fontSize: globals.fontSize,
  border: globals.border,
  margin: {
    blockTop: '0.5rem',
    dropDownToggleLeft: '0255rem',
  },
  padding: {
    sm: '0.25rem 0.5rem',
    lg: '0.5rem 1rem',
    default: '0.375rem 0.75rem',
    splitSmRight: '0.375rem',
    splitSmLeft: '0.375rem',
    splitLgRight: '0.75rem',
    splitLgLeft: '0.75rem',
    splitDefaultRight: '0.5625rem',
    splitDefaultLeft: '0.5625rem',
  },
  colors: {
    primary: {
      color: palette.white,
      colorOutline: palette.primary,
      colorOutlineHover: palette.white,
      backgroundColor: palette.primary,
      backgroundColorDisabled: palette.primary,
      backgroundColorHoverFocus: palette.primaryDarker,
      backgroundColorActive: palette.primaryDark,
      borderColor: palette.primary,
      borderColorDisabled: palette.primary,
      borderColorHoverFocus: palette.primaryDark,
      borderColorActive: palette.primaryDark,
      boxShadow: palette.primaryBoxShadow,
    },
    secondary: {
      color: palette.white,
      colorOutline: palette.secondary,
      colorOutlineHover: palette.white,
      backgroundColor: palette.secondary,
      backgroundColorDisabled: palette.secondary,
      backgroundColorHoverFocus: palette.secondaryDarker,
      backgroundColorActive: palette.secondary,
      borderColor: palette.secondary,
      borderColorDisabled: palette.secondary,
      borderColorHoverFocus: palette.secondaryDark,
      borderColorActive: palette.secondaryDark,
      boxShadow: palette.secondaryBoxShadow,
    },
    success: {
      color: palette.white,
      colorOutline: palette.success,
      colorOutlineHover: palette.white,
      backgroundColor: palette.success,
      backgroundColorDisabled: palette.success,
      backgroundColorHoverFocus: palette.successDarker,
      backgroundColorActive: palette.successDark,
      borderColor: palette.success,
      borderColorDisabled: palette.success,
      borderColorHoverFocus: palette.successDark,
      borderColorActive: palette.successDark,
      boxShadow: palette.successBoxShadow,
    },
    danger: {
      color: palette.white,
      colorOutline: palette.danger,
      colorOutlineHover: palette.white,
      backgroundColor: palette.danger,
      backgroundColorDisabled: palette.danger,
      backgroundColorHoverFocus: palette.dangerDarker,
      backgroundColorActive: palette.dangerDark,
      borderColor: palette.danger,
      borderColorDisabled: palette.danger,
      borderColorHoverFocus: palette.dangerDark,
      borderColorActive: palette.dangerDark,
      boxShadow: palette.dangerBoxShadow,
    },
    warning: {
      color: palette.darkerDarker,
      colorOutline: palette.warning,
      colorOutlineHover: palette.darkerDarker,
      backgroundColor: palette.warning,
      backgroundColorDisabled: palette.warning,
      backgroundColorHoverFocus: palette.warningDarker,
      backgroundColorActive: palette.warningDark,
      borderColor: palette.warning,
      borderColorDisabled: palette.warning,
      borderColorHoverFocus: palette.warningDark,
      borderColorActive: palette.warningDark,
      boxShadow: palette.warningBoxShadow,
    },
    info: {
      color: palette.white,
      colorOutline: palette.info,
      colorOutlineHover: palette.white,
      backgroundColor: palette.info,
      backgroundColorDisabled: palette.info,
      backgroundColorHoverFocus: palette.infoDarker,
      backgroundColorActive: palette.infoDark,
      borderColor: palette.info,
      borderColorDisabled: palette.info,
      borderColorHoverFocus: palette.infoDark,
      borderColorActive: palette.infoDark,
      boxShadow: palette.infoBoxShadow,
    },
    light: {
      color: palette.darkerDarker,
      colorOutline: palette.light,
      colorOutlineHover: palette.darkerDarker,
      backgroundColor: palette.light,
      backgroundColorDisabled: palette.light,
      backgroundColorHoverFocus: palette.lightDarker,
      backgroundColorActive: palette.lightDark,
      borderColor: palette.light,
      borderColorDisabled: palette.light,
      borderColorHoverFocus: palette.lightDark,
      borderColorActive: palette.lightDark,
      boxShadow: palette.lightBoxShadow,
      toggle: {
        color: palette.dark50Alpha,
        borderColor: palette.dark10Alpha,
        colorHoverFocus: palette.dark50Alpha,
        borderColorHoverFocus: palette.dark10Alpha,
      },
    },
    dark: {
      color: palette.white,
      colorOutline: palette.dark,
      colorOutlineHover: palette.white,
      backgroundColor: palette.dark,
      backgroundColorDisabled: palette.dark,
      backgroundColorHoverFocus: palette.darkDarker,
      backgroundColorActive: palette.darkDark,
      borderColor: palette.dark,
      borderColorDisabled: palette.dark,
      borderColorHoverFocus: palette.darkDark,
      borderColorActive: palette.darkDark,
      boxShadow: palette.darkBoxShadow,
      toggle: {
        color: palette.white50Alpha,
        borderColor: palette.white10Alpha,
        colorHoverFocus: palette.white50Alpha,
        borderColorHoverFocus: palette.white10Alpha,
      },
    },
    default: {
      color: palette.white,
      colorOutline: palette.secondary,
      colorOutlineHover: palette.white,
      backgroundColor: palette.secondary,
      backgroundColorDisabled: palette.secondary,
      backgroundColorHoverFocus: palette.secondaryDarker,
      backgroundColorActive: palette.secondary,
      borderColor: palette.secondary,
      borderColorDisabled: palette.secondary,
      borderColorHoverFocus: palette.secondaryDark,
      borderColorActive: palette.secondaryDark,
      boxShadow: palette.secondaryBoxShadow,
    },
  },
};

export default button;
