const listGroupItem = {
  colors: {
    primary: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'primaryDarkest'),
      backgroundColor: get => get('palette', 'primaryLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'primaryLighter'),
      backgroundColorActive: get => get('palette', 'primaryDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'primaryDarkest'),
      borderColorActive: get => get('palette', 'primaryDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    secondary: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'secondaryDarkest'),
      backgroundColor: get => get('palette', 'secondaryLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'secondaryLighter'),
      backgroundColorActive: get => get('palette', 'secondaryDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'secondaryDarkest'),
      borderColorActive: get => get('palette', 'secondaryDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    success: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'successDarkest'),
      backgroundColor: get => get('palette', 'successLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'successLighter'),
      backgroundColorActive: get => get('palette', 'successDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'successDarkest'),
      borderColorActive: get => get('palette', 'successDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    info: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'infoDarkest'),
      backgroundColor: get => get('palette', 'infoLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'infoLighter'),
      backgroundColorActive: get => get('palette', 'infoDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'infoDarkest'),
      borderColorActive: get => get('palette', 'infoDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    warning: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'warningDarkest'),
      backgroundColor: get => get('palette', 'warningLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'warningLighter'),
      backgroundColorActive: get => get('palette', 'warningDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'warningDarkest'),
      borderColorActive: get => get('palette', 'warningDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    danger: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'dangerDarkest'),
      backgroundColor: get => get('palette', 'dangerLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'dangerLighter'),
      backgroundColorActive: get => get('palette', 'dangerDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'dangerDarkest'),
      borderColorActive: get => get('palette', 'dangerDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    light: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'lightDarkest'),
      backgroundColor: get => get('palette', 'lightDark'),
      backgroundColorHoverFocusAction: get => get('palette', 'lightLighter'),
      backgroundColorActive: get => get('palette', 'lightDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'lightDarkest'),
      borderColorActive: get => get('palette', 'lightDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    dark: {
      colorDisabled: get => get('palette', 'lightDarker'),
      backgroundColorDisabled: get => get('palette', 'white'),
      colorActive: get => get('palette', 'white'),
      color: get => get('palette', 'darkDarkest'),
      backgroundColor: get => get('palette', 'darkLighter'),
      backgroundColorHoverFocusAction: get => get('palette', 'darkLighter'),
      backgroundColorActive: get => get('palette', 'darkDarkest'),
      backgroundColorHoverFocusActive: get => get('palette', 'darkDarkest'),
      borderColorActive: get => get('palette', 'darkDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
    },
    default: {
      colorDisabled: get => get('palette', 'lightDark'),
      backgroundColor: get => get('palette', 'white'),
      backgroundColorDisabled: get => get('palette', 'white'),
      backgroundColorAction: get => get('palette', 'light'),
      backgroundColorHoverFocusAction: get => get('palette', 'light'),
      color: get => get('palette', 'lightDarkest'),
      colorActive: get => get('palette', 'white'),
      colorAction: get => get('palette', 'lightDarkest'),
      borderColor: get => get('palette', 'weakBorder'),
      borderColorActive: get => get('palette', 'primary'),
      backgroundColorActive: get => get('palette', 'primary'),
    },
  },
  padding: {
    default: '0.75rem 1.25rem',
  },
  border: get => get('globals', 'border'),
  borderRadius: get => get('globals', 'borderRadius'),
};

export default listGroupItem;
